#import sharding-jdbc
spring:
  mvc:
    favicon:
      enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 6000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.seckill.seckillboot.dal.bean

# 主从读写分离
sharding:
  jdbc:
    datasource:
      names: master,slave1

      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ecommerce?characterEncoding=utf-8
        username: root
        password: root

      # 从数据源
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.102.201.85:3306/seckill?characterEncoding=utf-8
        username: root
        password: Root@2019

    # 读写分离配置
    config:
      masterslave:
        name: masterSlaveDataSource
        load-balance-algorithm-type: round_robin
        master-data-source-name: maste
        slave-data-source-names: slave1

#log
debug: true

##Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
      show-details: always

info:
  name: 基础平台SERVICE服务
  version: 1.0.0
