# 主从读写分离
sharding:
  jdbc:
    datasource:
      names: master,slave1

      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ecommerce?characterEncoding=utf-8
        username: root
        password: root

      # 从数据源
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.102.201.85:3306/seckill?characterEncoding=utf-8
        username: root
        password: Root@2019

  # 读写分离配置
    config:
      masterslave:
        name: masterSlaveDataSource
        load-balance-algorithm-type: round_robin
        master-data-source-name: master
        slaver-data-source-name: slave1
